export const carouselJumpProfile = {
  "version": 2,
  "preset": "reference-carousel-11",
  "model": "rfCarousel",
  "parameters": {
    "cycleDuration": 18,
    "easing": {
      "type": "easing",
      "duration": 1,
      "ease": [
        0.86,
        0.14,
        0.14,
        0.86
      ]
    },
    "queueAnimation": true,
    "queueStep": 100,
    "radiusPulse": 0,
    "scalePulse": 0,
    "opacityPulse": 0,
    "depthPulse": 0,
    "cardSize": 52.6,
    "cornerRadius": 0,
    "spacing": 21.76,
    "visible": 3,
    "offsetX": 0,
    "offsetY": 0,
    "direction": "right",
    "transitionDuration": 1.6,
    "delay": 0,
    "cycles": 1,
    "stagger": 0.06,
    "frontScale": 165,
    "scaleCenter": "on",
    "scaleFocus": "right",
    "tiltStyle": "off",
    "cardTilt": 0,
    "solo": false,
    "depthFade": 50,
    "shape": "line",
    "queue_units": "percent",
    "queue_customPath": "[[0,0.5],[1,0.5]]",
    "queue_fit": true,
    "queue_radiusX": 50,
    "queue_radiusY": 40,
    "queue_offsetX": 0,
    "queue_offsetY": 0,
    "queue_pathScale": 100,
    "queue_angle": 0,
    "queue_depth": 22.5,
    "queue_tilt": 0,
    "queue_turns": 1,
    "queue_rotation": 0,
    "queue_orient3d": false,
    "queue_shapeAmount": 1,
    "queue_spread": 100,
    "queue_depthFalloff": 1,
    "queue_xWave": "cos",
    "queue_yWave": "sin",
    "queue_depthWave": "sin",
    "queue_xFrequency": 1,
    "queue_yFrequency": 1,
    "queue_depthFrequency": 1,
    "queue_xAmplitude": 1,
    "queue_yAmplitude": 1,
    "queue_depthAmplitude": 0.2,
    "queue_xPhase": 0,
    "queue_yPhase": 0,
    "queue_depthPhase": 0,
    "queue_yOffset": 0,
    "shape_sizeBasis": "row",
    "shape_adaptiveSize": true,
    "shape_cardSize": 0,
    "shape_frontScale": 100,
    "shape_backScale": 100,
    "shape_backOpacity": 100,
    "shape_fadeStart": 0,
    "shape_fadeEnd": 100,
    "shape_opacityCurve": "linear",
    "shape_farBlur": 0,
    "shape_frontShadow": 0,
    "shape_facePath": false
  },
  "other": {
    "startOnEntry": true,
    "loopCardAnimation": false,
    "entryOffset": 0.2,
    "centerBeforeApply": true,
    "serviceLayers": "4",
    "scope": "selection"
  }
} as const;
