// @ts-nocheck
import assert from "node:assert/strict";
import { fromMotionDocument } from "./motion-system";
import { referenceScene } from "./reference-engine";
import { carouselJumpProfile } from "./test-fixtures/carousel-jump-profile";
import { share4909AuthoredCards } from "./test-fixtures/share-4909-authored-cards";
import { shareAuthoredCards } from "./test-fixtures/share-authored-cards";
import { freshPreset } from "./catalog";
import { toMotionDocument } from "./motion-system";

// Runs against the actual plugin entry point, not a replacement exporter.
// The host mock rounds/merges every track at the precision seen in Figma's
// readback of the reported frame. Comparing unrounded tracks hid this bug.
export async function runCarouselNativeRegressions(env) {
  const {makeNode,parent,topFrame,onMessage,nodes,postedMessages,sampleTrack,cloneData,setNativePrecision}=env;
  let configurations=0,playbackProbes=0,handoffProbes=0,nestedCopies=0,nestedForegroundProbes=0;
  let maximumGeometryError=0;
  Object.assign(topFrame,{width:1920,height:1280});
  Object.assign(parent,{width:1920,height:1280});
  setNativePrecision(true);

  function hydrate(input,root=false) {
    const node=makeNode(input.name);
    Object.assign(node,{type:input.type,width:input.width,height:input.height,opacity:input.opacity});
    node.relativeTransform=cloneData(input.relativeTransform);
    // Source root's OPACITY=0 was generated by the previous outer animation.
    // Its descendants retain their complete real authored tracks.
    node.manualKeyframeTracks=root?{}:cloneData(input.tracks);
    if(input.children){node.children=input.children.map(child=>hydrate(child));node.children.forEach(child=>child.parent=node);}
    return node;
  }
  function treeTracks(node) {
    return {tracks:cloneData(node.manualKeyframeTracks),children:(node.children??[]).map(treeTracks)};
  }
  async function apply(document,label) {
    const start=postedMessages.length;
    await onMessage({type:"apply",settings:document});
    const results=postedMessages.slice(start).filter(message=>message.type==="result");
    assert.equal(results.length,1,`${label}: exactly one result`);
    assert.notEqual(results[0].kind,"error",`${label}: ${results[0].message}`);
  }
  function slotsAt(root,time) {
    return root.children.filter(slot=>sampleTrack(slot.manualKeyframeTracks.OPACITY,time)>.5).map(slot=>{
      const artwork=slot.children.at(-1),source=shareAuthoredCards.findIndex(card=>card.name===artwork.name);
      return {source,slot,x:slot.x+slot.width/2+sampleTrack(slot.manualKeyframeTracks.TRANSLATION_X,time),
        y:slot.y+slot.height/2+sampleTrack(slot.manualKeyframeTracks.TRANSLATION_Y,time),
        width:slot.width*sampleTrack(slot.manualKeyframeTracks.SCALE_X,time),
        height:slot.height*sampleTrack(slot.manualKeyframeTracks.SCALE_Y,time),
        alpha:sampleTrack(artwork.manualKeyframeTracks.OPACITY,time)};
    });
  }
  function validate(root,settings,cards,label) {
    // Every property, including transforms, must survive native readback.
    const visit=node=>{
      for(const [field,track] of Object.entries(node.manualKeyframeTracks)){
        if(!track?.keyframes)continue;
        let previous=-1;
        for(const key of track.keyframes){
          assert(key.timelinePosition>=0&&Number.isFinite(key.timelinePosition),`${label}: valid ${field} time`);
          const micro=Math.round(key.timelinePosition*1e6);
          assert(micro>previous,`${label}: unique ${field} keys at native precision`);previous=micro;
        }
      }
      for(const child of node.children??[])visit(child);
    };visit(root);
    const duration=settings.motion.duration;
    // Uniform samples catch the multi-second deformation before a handoff,
    // rather than merely checking that keyframe timestamps are legal.
    const count=Math.ceil(duration*120);
    for(let index=0;index<=count;index++){
      const time=duration*index/count;
      const expected=referenceScene(settings,cards,1920,1280,time);
      const actual=slotsAt(root,time);
      assert.equal(actual.length,expected.length,`${label}: visible population at ${time}`);
      const remaining=[...actual];
      for(const card of expected){
        const candidates=remaining.filter(item=>item.source===card.source);
        const actualCard=candidates.sort((a,b)=>Math.hypot(a.x-card.x,a.y-card.y)-Math.hypot(b.x-card.x,b.y-card.y))[0];
        assert(actualCard,`${label}: source ${card.source} present at ${time}`);
        remaining.splice(remaining.indexOf(actualCard),1);
        const error=Math.max(...["x","y","width","height"].map(key=>Math.abs(actualCard[key]-card[key])));
        maximumGeometryError=Math.max(maximumGeometryError,error);
        assert(error<.08,`${label}: source ${card.source} geometry error ${error}px at ${time}s ${JSON.stringify({actual:[actualCard.x,actualCard.y,actualCard.width,actualCard.height],expected:card})}`);
        const alpha=(1-(card.shade??0))*(card.opacity??1)*cards[card.source].opacity;
        assert(Math.abs(actualCard.alpha-alpha)<.001,`${label}: effective artwork alpha at ${time}`);
      }
      for(const slot of root.children)if(sampleTrack(slot.manualKeyframeTracks.OPACITY,time)===0)
        assert.equal(sampleTrack(slot.children.at(-1).manualKeyframeTracks.OPACITY,time),0,`${label}: inactive artwork is hidden`);
      playbackProbes++;
    }
    // Independent continuity oracle: a persistent physical card must not
    // teleport, resize, or darken when its service-layer identity changes.
    const boundaries=new Set(root.children.flatMap(slot=>slot.manualKeyframeTracks.OPACITY.keyframes.map(key=>key.timelinePosition)));
    boundaries.add(0);boundaries.add(duration);
    for(const time of boundaries){
      const left=slotsAt(root,time<=.000002?duration-.000002:time-.000002);
      const right=slotsAt(root,time>=duration-.000002?.000002:time+.000002);
      for(const before of left){
        const after=right.filter(item=>item.source===before.source).sort((a,b)=>Math.hypot(a.x-before.x,a.y-before.y)-Math.hypot(b.x-before.x,b.y-before.y))[0];
        if(!after)continue;
        // A repeated source can legitimately occupy different offscreen slots;
        // only persistently onscreen cards participate in this continuity test.
        const onScreen=card=>card.x+card.width/2>0&&card.x-card.width/2<1920&&card.y+card.height/2>0&&card.y-card.height/2<1280;
        if(!onScreen(before)||!onScreen(after))continue;
        const error=Math.max(...["x","y","width","height"].map(key=>Math.abs(before[key]-after[key])));
        assert(error<.08,`${label}: source ${before.source} jumps ${error}px at handoff ${time} ${JSON.stringify({before:[before.x,before.y,before.width,before.height],after:[after.x,after.y,after.width,after.height],settings,sizes:cards.map(c=>({width:c.width,height:c.height})),left:referenceScene(settings,cards,1920,1280,time-.000002),right:referenceScene(settings,cards,1920,1280,time+.000002)})}`);
        assert(Math.abs(before.alpha-after.alpha)<.001,`${label}: handoff alpha continuity`);
        handoffProbes++;
      }
    }
    // Every depth copy of a given card uses the same complete nested playback.
    for(const source of shareAuthoredCards){
      const instances=root.children.filter(slot=>slot.children.at(-1).name===source.name).map(slot=>slot.children.at(-1));
      const baseline=(instances[0]?.children??[]).map(treeTracks);
      for(const instance of instances){assert.deepEqual((instance.children??[]).map(treeTracks),baseline,`${label}: nested playback continuous across ${source.name} copies`);nestedCopies++;}
    }
    if(label==="right/visible=3"){
      // Determine foreground occurrences from the continuous scene, without
      // using the exporter's mainCardOccurrences or nested retiming functions.
      const winner=time=>referenceScene(settings,cards,1920,1280,time).sort((a,b)=>
        Math.hypot(a.x-960,a.y-640)-Math.hypot(b.x-960,b.y-640))[0]?.source;
      const events=[];let previous=winner(0);
      for(let i=1;i<=duration*240;i++){
        const end=Math.min(duration,i/240),next=winner(end);
        if(next!==previous){
          let lo=(i-1)/240,hi=end;
          for(let iteration=0;iteration<40;iteration++){const mid=(lo+hi)/2;if(winner(mid)===previous)lo=mid;else hi=mid;}
          if(hi<duration-1e-6)events.push({source:next,time:hi});
        }
        previous=next;
      }
      assert.equal(new Set(events.map(event=>event.source)).size,cards.length,"Every card has an independently found foreground occurrence");
      for(const event of events)for(const elapsed of [.2,.35,.5]){
        const time=(event.time+settings.other.entryOffset+elapsed)%duration;
        const instance=slotsAt(root,time).find(item=>item.source===event.source)?.slot.children.at(-1);
        assert(instance,`Foreground ${event.source} remains visible during its reveal`);
        const actual=sampleTrack(instance.children[0].children[0].manualKeyframeTracks.OPACITY,time);
        const authored=sampleTrack(shareAuthoredCards[event.source].children[0].children[0].tracks.OPACITY,elapsed);
        // Foreground detection is sampled at >=90Hz. Bound its possible
        // subframe timing difference while checking the actual authored curve.
        assert(Math.abs(actual-authored)<.025,`Source ${event.source} nested reveal matches its independently derived start`);
        nestedForegroundProbes++;
      }
      const before=slotsAt(root,duration),after=slotsAt(root,0);
      for(const outgoing of before){
        const incoming=after.find(item=>item.source===outgoing.source);
        assert(incoming,"Same physical card exists at both timeline ends");
        const compare=(a,b)=>{
          for(const [field,track] of Object.entries(a.manualKeyframeTracks))if(track?.keyframes?.length&&track.keyframes.every(key=>key.value.type==="FLOAT")&&b.manualKeyframeTracks[field])
            for(const [leftTime,rightTime,tolerance] of [[duration,0,.00001],[duration-.000002,.000002,.01]])
              assert(Math.abs(sampleTrack(track,leftTime)-sampleTrack(b.manualKeyframeTracks[field],rightTime))<tolerance,`Source ${outgoing.source} nested ${field} seam at ${leftTime}/${rightTime}`);
          (a.children??[]).forEach((child,index)=>compare(child,b.children[index]));
        };
        // Root artwork is already checked above; include all descendants.
        outgoing.slot.children.at(-1).children.forEach((child,index)=>compare(child,incoming.slot.children.at(-1).children[index]));
      }
    }
  }
  const variants=[];
  for(const direction of ["right","left","up","down"])for(const visible of [1,3,6])
    variants.push({label:`${direction}/visible=${visible}`,parameters:{direction,visible}});
  variants.push({label:"large nested storage cap",largeNested:true,parameters:{direction:"up",visible:6,queueAnimation:true},other:{startOnEntry:true,loopCardAnimation:true,entryOffset:-.4}},
    {label:"reported settings storage cap",exact4909:true,parameters:{direction:"up",visible:6,queueAnimation:true},other:{startOnEntry:true,loopCardAnimation:true,entryOffset:-.4}},
    {label:"center focus",parameters:{scaleFocus:"center"}},
    {label:"left focus",parameters:{scaleFocus:"left"}},
    {label:"continuous queue off",parameters:{queueAnimation:false}},
    {label:"nested timing off",other:{startOnEntry:false}},
    {label:"nested repeat",other:{loopCardAnimation:true,startOnEntry:false}},
    {label:"negative entry offset",other:{entryOffset:-.2}},
    {label:"three cycles",parameters:{cycles:3}},
    {label:"linear timing",parameters:{easing:{type:"easing",duration:1,ease:[0,0,1,1]}}},
    {label:"two sources repeated",sourceCount:2,parameters:{visible:6}},
    {label:"three sources repeated",sourceCount:3,parameters:{visible:6}});
  try {
    for(const variant of variants.filter(item=>!env.onlyLabel||item.label===env.onlyLabel)){
      const cards=(variant.exact4909?share4909AuthoredCards:shareAuthoredCards).slice(0,variant.sourceCount??6).map(card=>hydrate(card,true));
      if(variant.largeNested){
        const track=cards[0].children[0].children[0].manualKeyframeTracks.OPACITY;
        track.keyframes=Array.from({length:241},(_,index)=>({timelinePosition:index/200,value:{type:"FLOAT",value:index/240},easing:{type:"LINEAR"}}));
      }
      parent.children=cards;globalThis.figma.currentPage.selection=cards;
      const originals=cards.map(treeTracks);
      const document=variant.exact4909?toMotionDocument(freshPreset("reference-carousel-05")):cloneData(carouselJumpProfile);
      Object.assign(document.parameters,variant.parameters??{});if(variant.exact4909)document.parameters.cycleDuration=18;Object.assign(document.other,variant.other??{});
      const settings=fromMotionDocument(document);
      await apply(document,variant.label);
      const root=nodes.get(JSON.parse(cards[0].getPluginData("orbit-motion")).serviceIds[0]);
      validate(root,settings,cards,variant.label);
      if(variant.label==="reported settings storage cap"||variant.largeNested){
        let maximumMarkerBytes=0;
        const inspect=node=>{
          const raw=node.getPluginData("orbit-entry-motion");
          if(raw){const header=JSON.parse(raw);const full=header.version===2?Array.from({length:header.count},(_,index)=>node.getPluginData(`orbit-entry-motion:${header.bank}:${index}`)).join(""):raw;maximumMarkerBytes=Math.max(maximumMarkerBytes,Buffer.byteLength(full,"utf8"));}
          (node.children??[]).forEach(inspect);
        };inspect(root);
        if(variant.largeNested||variant.exact4909)assert(maximumMarkerBytes>100000,"Full pipeline must generate a marker larger than the original native limit");
        console.log(`Full exporter storage cap: ${variant.label}; maximum logical marker ${maximumMarkerBytes} bytes; native100kB per entry enforced`);
        const first=treeTracks(root);
        for(let repeat=0;repeat<3;repeat++){
          globalThis.figma.currentPage.selection=cards;
          await apply(document,`reported settings storage cap Refresh ${repeat}`);
          const refreshed=nodes.get(JSON.parse(cards[0].getPluginData("orbit-motion")).serviceIds[0]);
          assert.deepEqual(treeTracks(refreshed),first,"100kB storage-cap Refresh preserves every track without accumulated offset");
          validate(refreshed,settings,cards,`reported storage cap Refresh ${repeat}`);
        }
      }
      // Exercise Refresh with the exact profile and its last-source selection.
      if(variant.label==="right/visible=3"){
        const first=treeTracks(root);globalThis.figma.currentPage.selection=[cards.at(-1)];
        await apply(document,"exact last-card Refresh");
        const refreshed=nodes.get(JSON.parse(cards[0].getPluginData("orbit-motion")).serviceIds[0]);
        assert.deepEqual(treeTracks(refreshed),first,"Exact Refresh preserves complete exported playback");
        assert(!nodes.has(root.id),"Exact Refresh removes stale service output");
        validate(refreshed,settings,cards,"exact Refresh");
        for(const intermediate of ["reference-stack-01","circle"]){
          globalThis.figma.currentPage.selection=cards;
          await apply(toMotionDocument(freshPreset(intermediate,settings)),`exact → ${intermediate}`);
          globalThis.figma.currentPage.selection=cards;
          await apply(document,`${intermediate} → exact`);
          const restored=nodes.get(JSON.parse(cards[0].getPluginData("orbit-motion")).serviceIds[0]);
          assert.deepEqual(treeTracks(restored),first,`${intermediate} → exact restores every outer and nested track`);
        }
      }
      globalThis.figma.currentPage.selection=[cards.at(-1)];
      const start=postedMessages.length;await onMessage({type:"clear",scope:"selection"});
      assert(!postedMessages.slice(start).some(message=>message.kind==="error"),`${variant.label}: Clear succeeds`);
      assert.deepEqual(cards.map(treeTracks),originals,`${variant.label}: Clear restores every authored nested track`);
      assert(parent.children.every(node=>!node.name.includes("Orbit native")),`${variant.label}: no service output remains`);
      configurations++;
    }
  } finally {setNativePrecision(false);}
  console.log(`Native carousel precision: ${configurations} settings + exact Refresh + Stack/Orbit round trips; ${playbackProbes} playback and ${handoffProbes} continuity probes; ${nestedCopies} nested copies, ${nestedForegroundProbes} independent nested-start probes; max geometry error ${maximumGeometryError.toFixed(5)}px`);
}
